### ISSUE TITLE
`Error: Can only create NonNull of a Nullable GraphQLType but got: String.`

### ISSUE THREAD

**Issue by vjpr** [graphile/graphile-build#120]
In `postgraphile@^4.0.0-alpha2.24`. I am printing what is passed to `type` at the location of the error:

```
} : null, keys.reduce((memo, key) => {
  memo[inflection.column(key.name, key.class.name, key.class.namespace.name)] = {
    type: new GraphQLNonNull(pgGetGqlInputTypeByTypeId(key.typeId))
  };
```

```
{ key:
   { kind: 'attribute',
     classId: '207155',
     num: 1,
     name: 'id',
     description: null,
     typeId: '1043',
     isNotNull: true,
     hasDefault: false,
     class:
      { kind: 'class',
        id: '207155',
        name: 'address',
        classKind: 'r',
        description: null,
        namespaceId: '2200',
        namespaceName: 'public',
        typeId: '207157',
        isSelectable: true,
        isInsertable: true,
        isUpdatable: true,
        isDeletable: true,
        namespace: [Object],
        type: [Object] },
     type:
      { kind: 'type',
        id: '1043',
        name: 'varchar',
        description: 'varchar(length), non-blank-padded string, variable storage length',
        namespaceId: '11',
        namespaceName: 'pg_catalog',
        type: 'b',
        category: 'S',
        domainIsNotNull: false,
        arrayItemTypeId: null,
        classId: null,
        domainBaseTypeId: null,
        enumVariants: null,
        rangeSubTypeId: null,
        class: undefined,
        domainBaseType: undefined,
        arrayItemType: undefined } } }
An error occurred, it might be okay but it doesn't look like the error we were expecting... run with envvar 'DEBUG="graphile-build:warn"' to view the error
  graphile-build:warn Error: Can only create NonNull of a Nullable GraphQLType but got: String.
  graphile-build:warn     at invariant (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphql/0.11.7/node_modules/graphql/jsutils/invariant.js:18:11)
  graphile-build:warn     at new GraphQLNonNull (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphql/0.11.7/node_modules/graphql/type/definition.js:779:84)
  graphile-build:warn     at newWithHooks.fields.keys.reduce (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build-pg/0.1.0-alpha.35/graphql@0.11.7+pg@6.4.2/node_modules/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js:421:33)
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at uniqueConstraints.forEach.constraint (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build-pg/0.1.0-alpha.35/graphql@0.11.7+pg@6.4.2/node_modules/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js:412:32)
  graphile-build:warn     at Array.forEach (<anonymous>)
  graphile-build:warn     at introspectionResultsByKind.class.filter.filter.reduce (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build-pg/0.1.0-alpha.35/graphql@0.11.7+pg@6.4.2/node_modules/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js:367:37)
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at extend.reduce (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build-pg/0.1.0-alpha.35/graphql@0.11.7+pg@6.4.2/node_modules/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js:61:16)
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at PgMutationUpdateDeletePlugin.builder.hook (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build-pg/0.1.0-alpha.35/graphql@0.11.7+pg@6.4.2/node_modules/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js:52:30)
  graphile-build:warn     at SchemaBuilder.applyHooks (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build/0.1.0-alpha.32/graphql@0.11.7/node_modules/graphile-build/src/SchemaBuilder.js:289:20)
  graphile-build:warn     at fields (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build/0.1.0-alpha.32/graphql@0.11.7/node_modules/graphile-build/src/makeNewBuild.js:440:40)
  graphile-build:warn     at resolveThunk (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphql/0.11.7/node_modules/graphql/type/definition.js:168:40)
  graphile-build:warn     at defineFieldMap (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphql/0.11.7/node_modules/graphql/type/definition.js:349:18)
  graphile-build:warn     at GraphQLObjectType.getFields (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphql/0.11.7/node_modules/graphql/type/definition.js:310:44)
  graphile-build:warn     at Object.newWithHooks (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build/0.1.0-alpha.32/graphql@0.11.7/node_modules/graphile-build/src/makeNewBuild.js:579:18)
  graphile-build:warn     at MutationPlugin.builder.hook (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build/0.1.0-alpha.32/graphql@0.11.7/node_modules/graphile-build/src/plugins/MutationPlugin.js:8:24)
  graphile-build:warn     at SchemaBuilder.applyHooks (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build/0.1.0-alpha.32/graphql@0.11.7/node_modules/graphile-build/src/SchemaBuilder.js:289:20)
  graphile-build:warn     at Object.newWithHooks (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build/0.1.0-alpha.32/graphql@0.11.7/node_modules/graphile-build/src/makeNewBuild.js:225:27)
  graphile-build:warn     at SchemaBuilder.buildSchema (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/graphile-build/0.1.0-alpha.32/graphql@0.11.7/node_modules/graphile-build/src/SchemaBuilder.js:341:37)
  graphile-build:warn     at Object.exports.createPostGraphQLSchema (xxx/packages/intranav-graphql/node_modules/.registry.npmjs.org/postgraphile-core/0.1.0-alpha.35/graphql@0.11.7+pg@6.4.2/node_modules/postgraphile-core/src/index.js:138:18)
  graphile-build:warn     at <anonymous>
  graphile-build:warn     at process._tickCallback (internal/process/next_tick.js:188:7) +1ms
  ```

**Comment by benjie** [comment]
This smells like a GraphQL version conflict; i.e. there are two GraphQL modules fighting.

**Comment by benjie** [comment]
Looking at the stack tract, what package manager are you using? Those paths look different. Not npm or yarn by the looks of it?

**Comment by vjpr** [comment]
> This smells like a GraphQL version conflict

This is probably what it is. I am using a Lerna monorepo and have two packages that both do graphql stuff.

> what package manager are you using

pnpm

**Comment by benjie** [comment]
So I think pnpm has installed multiple versions of `graphql` unnecessarily (you can see from the paths that they're all targetting 0.11.7) - I would suggest switching over to yarn (maybe using yarn workspaces?) or npm with lerna.

**Comment by benjie** [comment]
@vjpr  Did you get this sorted?

**Comment by vjpr** [comment]
@benjie Will try it out soon. Postgraphql working fine for me atm.

**Comment by benjie** [comment]
[semi-automated message] To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.
