### ISSUE TITLE
support output tables on function mutations

### ISSUE THREAD

**Issue by stlbucket** [graphile/graphile-build#147]
is it possible to support this?

```
CREATE OR REPLACE FUNCTION public.search_total_sales_by_customer(
  _id uuid,
  _start_date text,
  _end_date text
)
RETURNS TABLE (
    seller_name   text
  , customer_name   TEXT
  , total_sales NUMERIC(20,2)
) 
as $$
BEGIN
  RETURN QUERY
  SELECT ...   -- whatever the logic should be
  ;
END;
$$ language plpgsql strict security definer;
--||--
GRANT execute ON FUNCTION public.search_total_sales_by_customer(
  uuid, 
  text,
  text
) TO public_user;
```

postgraphile doesn't pick up this function as a mutation.   if i change the return type to boolean, it's fine, so i'm sure it's the return type.

is this possibly related to: https://github.com/graphile/graphile-build/issues/132

**Comment by stlbucket** [comment]
workaround for this is:

```
RETURNS JSONB
as $$
DECLARE
  _retval jsonb;
BEGIN

  SELECT array_to_json(array_agg(row_to_json(t))) INTO _retval
  FROM ...
  ...
  RETURN _retval;
```

**Comment by benjie** [comment]
PostGraphQL does not (currently) support anonymous types. Please use a named return type (e.g. “create type foo as (col1 text, col2 int, ...)” or “create table foo (col1 text, col2 int, ...)”)

https://www.graphile.org/postgraphile/custom-mutations/

**Comment by stlbucket** [comment]
will do

**Comment by stlbucket** [comment]
ok - i've got something like this:

```
CREATE TYPE soro.total_sales_period_report AS (
  seller_name text,
  report_type soro.seller_report_type,
  time_division soro.time_division,
  filter_type soro.total_sales_filter_type,
  filter_value text,
  period_start_date text,
  period_end_date text,
  total_sales numeric(50,2),
  total_units numeric(50,2),
  avg_price_per_unit numeric(20,2),
  seller_id uuid
);

CREATE OR REPLACE FUNCTION soro.execute_total_sales_report(
  _seller_id uuid,
  _report_type soro.seller_report_type,
  _time_division soro.time_division,
  _start_date text,
  _end_date text,
  _filter_type soro.total_sales_filter_type,
  _filter_value text
)
RETURNS soro.total_sales_period_report[]
...
```

i'm seeing the output i want to see from this at the postgres level, and graphql properly helps me build the query:
```
mutation ExecuteTotalSalesReport(
  $sellerId: UUID!
	$reportType: SellerReportType!
	$timeDivision: TimeDivision!
	$startDate: String!
	$endDate: String!
	$filterType: TotalSalesFilterType!
	$filterValue: String!
) {
  executeTotalSalesReport(input: {
    _sellerId: $sellerId
    _reportType: $reportType
    _timeDivision: $timeDivision
    _startDate: $startDate
    _endDate: $endDate
    _filterType: $filterType
    _filterValue: $filterValue
  }) {
    totalSalesPeriodReports {
      sellerName
      reportType
      timeDivision
      filterType
      filterValue
			periodStartDate
      periodEndDate
      periodYear
      periodQuarter
      periodMonthDisplay
      periodMonthNum
      periodWeek
      totalSales
      totalUnits
      avgPricePerUnit
      sellerId
    }
  }
}
```
but when i execute the query:
```
{
  "errors": [
    {
      "message": "type soro.total_sales_period_report[] is not composite",
      "locations": [
        {
          "line": 10,
          "column": 3
        }
      ],
      "path": [
        "executeTotalSalesReport"
      ],
      "stack": "error: type soro.total_sales_period_report[] is not composite\n    at Connection.parseE (/Users/buckfactor/soro/bitbucket/soro/sales/api/node_modules/pg/lib/connection.js:567:11)\n    at Connection.parseMessage (/Users/buckfactor/soro/bitbucket/soro/sales/api/node_modules/pg/lib/connection.js:391:17)\n    at Socket.<anonymous> (/Users/buckfactor/soro/bitbucket/soro/sales/api/node_modules/pg/lib/connection.js:129:22)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at addChunk (_stream_readable.js:252:12)\n    at readableAddChunk (_stream_readable.js:239:11)\n    at Socket.Readable.push (_stream_readable.js:197:10)\n    at TCP.onread (net.js:589:20)"
    }
  ],
  "data": {
    "executeTotalSalesReport": null
  }
}
```

am i doing something wrong?

**Comment by benjie** [comment]
Hey @stlbucket this is a completely different issue - would you mind opening a different ticket for it? e.g. "type soro.total_sales_period_report[] is not composite error when returning array of composite type from mutation"

Also, please can you confirm you're running 4.0.0-alpha2.28 because I think I fixed some issues like this a release or two ago.
