### ISSUE TITLE
Adding/removing fields from a GraphQLInputObjectType via a hook

### ISSUE THREAD

**Issue by cemulate** [graphile/graphile-build#227]
I'm submitting a ...

- [ ] bug report
- [ ] feature request
- [x] question

I'm using `postgraphile@4.0.0-beta.9` / `postgraphile-core@4.0.0-beta.7`

I'm trying to extend postgraphile by writing a plugin to add a field to a mutation's `input` object. Per the [documentation on hooks](https://www.graphile.org/graphile-build/all-hooks/):

> `GraphQLInputObjectType:fields` to add additional fields to this object type (is ran asynchronously and gets a reference to the final GraphQL Object as Self in the context)

So my attempt at adding an argument to the input object for my mutation was as follows:

```js
module.exports = function RecaptchaPlugin(builder) {
    builder.hook('GraphQLInputObjectType:fields', (fields, build, context) => {
        let pluginApplies = context.scope.isMutationInput 
                         && context.GraphQLInputObjectType.name == 'RegisterUserInput';

        if (!pluginApplies) return fields;

        return build.extend(fields, {
            recaptchaResponse: {
                type: 'String!',
            },
        });
    });
}
```

But this produces (upon the introspection query):

```
Error: The type of RegisterUserInput.recaptchaResponse must be Input Type but got: String!.

Expected GraphQL named type but got: String!.
at assertValidSchema (/app/node_modules/graphql/type/validate.js:78:11)
at Object.validate (/app/node_modules/graphql/validation/validate.js:61:35)
at Promise.all.paramsList.map (/app/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:413:56)
at Array.map (<anonymous>)
at requestHandler (/app/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:360:52)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

Which seems suspect as, when logging the rest of the fields, they are of type `String!`:

```js
{ clientMutationId: { type: String },
firstName: { type: String! },
lastName: { type: String! },
email: { type: String! },
password: { type: String! } }
```

The documentation is a little vague, so I'm not entirely sure if I'm doing this correctly. My goal is to add an additional field to the input type for this mutation (and later wrap the resolver to do additional work with it). Am I missing something simple here?

**Comment by benjie** [comment]
Yep you got it - you were passing a string where GraphQL expected an object. I really like your syntax though- would love to make that work in future!

The docs repo is OSS; I’d love a PR to it that made this clearer. I’m in too deep, it’s hard for me to pitch things at the right level.

https://github.com/graphile/graphile.github.io

**Comment by cemulate** [comment]
Thanks @benjie - I'll take a look at adding that to the docs.

Is there a collection of plugin examples anywhere? I think that recaptcha integration with a "register" mutation is a pretty common use case, so I'd love to publish the plugin once I polish it up.

**Comment by benjie** [comment]
There’s https://github.com/graphile-contrib

https://github.com/graphile/postgraphile/wiki/Plugins

https://github.com/graphile/graphile.github.io/tree/develop/examples

👍👍👍

**Comment by mattbretl** [comment]
I'm actually working on a restructured version of the All Hooks page of the docs:

https://github.com/mattbretl/graphile.github.io/blob/all-hooks-rewrite/src/pages/graphile-build/all-hooks.md

Once Benjie merges https://github.com/graphile/graphile-build/pull/226, I'll be adding adding links to usage examples from the graphile-build/graphile-build-pg source (and maybe from some contrib plugins as well).

Any feedback on this would be greatly appreciated.
