### ISSUE TITLE
Type 'Subscription' has already been registered

### ISSUE THREAD

**Issue by saerdnaer** [graphile/graphile-build#237]
When the postgres schema has a relation named `subscriptions` running postgraphile crashes with following error. Renaming the relation resolved the problem.

```
Error: Type 'Subscription' has already been registered!
    at Object.newWithHooks (node_modules/graphile-build/src/makeNewBuild.js:721:17)
    at SubscriptionPlugin.builder.hook (node_modules/graphile-build/src/plugins/SubscriptionPlugin.js:21:26)
    at SchemaBuilder.applyHooks (node_modules/graphile-build/src/SchemaBuilder.js:250:20)
    at Object.newWithHooks (node_modules/graphile-build/src/makeNewBuild.js:296:27)
    at SchemaBuilder.buildSchema (node_modules/graphile-build/src/SchemaBuilder.js:311:37)
    at SchemaBuilder.watchSchema (node_modules/graphile-build/src/SchemaBuilder.js:342:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by benjie** [comment]
You can also use smart comments: `comment on table subscriptions is E'@name Subs';`

**Comment by benjie** [comment]
(This is because PostGraphile uses the standard types: Query, Mutation and Subscription.)

**Comment by saerdnaer** [comment]
Just for sake of completeness: `@omit all` did not yield the same result, only renaming via `@name xxx` worked.

**Comment by benjie** [comment]
`@omit all` only omits the 'allSubscriptions' field (not the type itself, which is what is conflicting here). You want `@omit` or `@omit *` if you prefer being explicit.

**Comment by saerdnaer** [comment]
Is it also possible to omit the whole relation via a graphile-build plugin?

**Comment by benjie** [comment]
Yeah; but that's going to be a lot more effort than a smart comment.

https://www.graphile.org/postgraphile/smart-comments/

**Comment by saerdnaer** [comment]
My idea was to run our old v3 based graphql service in parallel with the new v4 one, and thought a  smart comment would be honoured by both. This is not the case as the`@name` is only parsed by postgraphile. :-)

**Comment by benjie** [comment]
Yeah they’re a very new feature. You’ve got another couple options; one is to skip the Subscriptions plugin being loaded, another is to add a plugin that renames the subscription type.
