### ISSUE TITLE
gql2pg should be called with three arguments, the third being the type modifier (or `null`); Error

### ISSUE THREAD

**Issue by vjpr** [graphile/graphile-build#253]
Maybe related to `postgraphile-plugin-connection-filter`?

```
gql2pg should be called with three arguments, the third being the type modifier (or `null`); Error
    at Object.gql2pg (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/graphile-build-pg/4.0.0-rc.4/graphql@0.12.3+pg@7.4.3/node_modules/graphile-build-pg/src/plugins/PgTypesPlugin.js:138:17)
    at valFromInput (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/postgraphile-plugin-connection-filter/1.0.0-beta.13/node_modules/postgraphile-plugin-connection-filter/src/PgConnectionArgFilterPlugin.js:400:33)
    at resolveWhereComparison (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/postgraphile-plugin-connection-filter/1.0.0-beta.13/node_modules/postgraphile-plugin-connection-filter/src/PgConnectionArgFilterPlugin.js:417:21)
    at sql.query.sql.join.Object.entries.map (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/postgraphile-plugin-connection-filter/1.0.0-beta.13/node_modules/postgraphile-plugin-connection-filter/src/PgConnectionArgFilterPlugin.js:477:23)
    at Array.map (<anonymous>)
    at entries.map (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/postgraphile-plugin-connection-filter/1.0.0-beta.13/node_modules/postgraphile-plugin-connection-filter/src/PgConnectionArgFilterPlugin.js:476:43)
    at Array.map (<anonymous>)
    at resolveWhereLogic (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/postgraphile-plugin-connection-filter/1.0.0-beta.13/node_modules/postgraphile-plugin-connection-filter/src/PgConnectionArgFilterPlugin.js:451:42)
    at pgQuery (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/postgraphile-plugin-connection-filter/1.0.0-beta.13/node_modules/postgraphile-plugin-connection-filter/src/PgConnectionArgFilterPlugin.js:487:34)
    at Object.exports.default (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/graphile-build-pg/4.0.0-rc.4/graphql@0.12.3+pg@7.4.3/node_modules/graphile-build-pg/src/queryFromResolveData.js:45:5)
    at resolve (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/graphile-build-pg/4.0.0-rc.4/graphql@0.12.3+pg@7.4.3/node_modules/graphile-build-pg/src/plugins/PgAllRows.js:104:35)
    at resolveFieldValueOrError (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/graphql/0.12.3/node_modules/graphql/execution/execute.js:544:18)
    at resolveField (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/graphql/0.12.3/node_modules/graphql/execution/execute.js:508:16)
    at xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/graphql/0.12.3/node_modules/graphql/execution/execute.js:357:18
    at Array.reduce (<anonymous>)
    at executeFields (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/graphql/0.12.3/node_modules/graphql/execution/execute.js:354:42)
    at executeOperation (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/graphql/0.12.3/node_modules/graphql/execution/execute.js:278:122)
    at executeImpl (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/graphql/0.12.3/node_modules/graphql/execution/execute.js:142:14)
    at Object.execute (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/graphql/0.12.3/node_modules/graphql/execution/execute.js:119:229)
    at graphqlContext (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/postgraphile/4.0.0-rc.2/node_modules/postgraphile/src/postgraphile/http/createPostGraphileHttpRequestHandler.js:669:22)
    at withPostGraphileContext_1.default.context (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/postgraphile/4.0.0-rc.2/node_modules/postgraphile/src/postgraphile/http/createPostGraphileHttpRequestHandler.js:122:16)
    at withDefaultPostGraphileContext (xxx/packages/xxx/xxx/xxx-graphql/node_modules/.registry.npmjs.org/postgraphile/4.0.0-rc.2/node_modules/postgraphile/src/postgraphile/withPostGraphileContext.ts:111:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by benjie** [comment]
This is just a warning, we automatically fall back to using `null` as the type modifier.

https://github.com/graphile/graphile-build/blob/b3c4d0754f03a1319cfd119c542d4a987bc4df2f/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L142-L148

But yes, it's `postgraphile-plugin-connection-filter` using the old API; feel free to raise an issue against that repo.
