### ISSUE TITLE
Improve error message for field clashes

### ISSUE THREAD

**Issue by danscan** [graphile/graphile-build#46]
I had attempted to create a computed field called like `my_schema.funding_round_status(funding_round my_schema.funding_round)`.  After restarting the process, I encountered the following error during introspection:

```
Error: Overwriting key 'status' is not allowed!
    at Object.extend (/usr/src/app/node_modules/graphile-build/node8plus/makeNewBuild.js:141:17)
    at PgComputedColumnsPlugin.builder.hook (/usr/src/app/node_modules/graphile-build-pg/node8plus/plugins/PgComputedColumnsPlugin.js:35:12)
    at SchemaBuilder.applyHooks (/usr/src/app/node_modules/graphile-build/node8plus/SchemaBuilder.js:149:20)
    at fields (/usr/src/app/node_modules/graphile-build/node8plus/makeNewBuild.js:308:40)
    at resolveThunk (/usr/src/app/node_modules/graphql/type/definition.js:169:40)
    at defineFieldMap (/usr/src/app/node_modules/graphql/type/definition.js:350:18)
    at GraphQLObjectType.getFields (/usr/src/app/node_modules/graphql/type/definition.js:311:44)
```

**Comment by benjie** [comment]
That implies there is already a status field on that object. If you share your full schema with me privately I can help figure it out.

**Comment by danscan** [comment]
@benjie You're totally right :).  A change was made to the schema file, but wasn't applied to the right database.  Oops -_-

**Comment by benjie** [comment]
How could we have improved the error message? Can you confirm exactly what occurred? (What was the duplicate - a column and a computed function, maybe?)

**Comment by danscan** [comment]
@benjie There was a column `status` on the table `funding_round` (I had thought it was removed, but that wasn't the case), and a function `funding_round_status`.

The error message might be improved by adding the table name?  e.g. `Overwriting key 'status' of type `FundingRound` is not allowed!`

**Comment by chadfurman** [comment]
I also had this problem -- I made a procedure called "liveroom_by_hash", but the field was unique and so there was a conflicting function name generated.  Took a bit to figure that out.
