### ISSUE TITLE
graphile-build-pg chokes on enums that contain the empty string as a value

### ISSUE THREAD

**Issue by benjie** [graphile/graphile-build#76]
To reproduce:

```
$ createdb issue-76
$ echo "create type foo as enum('', 'one', 'two');" | psql issue-76
SET
Time: 29.167 ms
CREATE TYPE
Time: 4.223 ms
$ postgraphile --version
4.0.0-alpha2.19
$ postgraphile -c postgres://localhost/issue-76

PostGraphQL server listening on port 5000 🚀

  ‣ Connected to Postgres instance postgres://localhost:5432/issue-76
  ‣ Introspected Postgres schema(s) public
  ‣ GraphQL endpoint served at http://localhost:5000/graphql
  ‣ GraphiQL endpoint served at http://localhost:5000/graphiql

* * *

Error: Must be named. Unexpected name: .
    at assertValidName (/Users/benjiegillam/.nvm/versions/node/v8.4.0/lib/node_modules/postgraphile/node_modules/graphql/utilities/assertValidName.js:32:11)
    at /Users/benjiegillam/.nvm/versions/node/v8.4.0/lib/node_modules/postgraphile/node_modules/graphql/type/definition.js:632:42
    at Array.map (<anonymous>)
    at defineEnumValues (/Users/benjiegillam/.nvm/versions/node/v8.4.0/lib/node_modules/postgraphile/node_modules/graphql/type/definition.js:631:21)
    at new GraphQLEnumType (/Users/benjiegillam/.nvm/versions/node/v8.4.0/lib/node_modules/postgraphile/node_modules/graphql/type/definition.js:549:20)
    at enforceGqlTypeByPgType (/Users/benjiegillam/.nvm/versions/node/v8.4.0/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgTypesPlugin.js:343:36)
    at Array.forEach (<anonymous>)
    at PgTypesPlugin.builder.hook.build (/Users/benjiegillam/.nvm/versions/node/v8.4.0/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgTypesPlugin.js:497:37)
    at SchemaBuilder.applyHooks (/Users/benjiegillam/.nvm/versions/node/v8.4.0/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:149:20)
    at SchemaBuilder.createBuild (/Users/benjiegillam/.nvm/versions/node/v8.4.0/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:177:24)
```

**Comment by benjie** [comment]
(Also note that this error is **extremely** unhelpful.)

**Comment by benjie** [comment]
v3 also suffers this issue, but only if the type is actually used in the schema (whereas v4 creates the types ahead of time currently)

```sql
create function bar() returns foo as $$ select null::foo; $$ language sql stable;
```
